name: Build and Push Nginx Image

on:
  push:
    branches:
      - master  # 触发工作流的分支，通常是 main 或 master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Hugo site
        run: |
          docker run --rm -v $(pwd):/src hugomods/hugo:exts hugo --minify --baseURL "${{ secrets.HUGO_BASEURL }}"

      - name: Build and push Nginx image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hugo-nginx:${{ env.TIMESTAMP }}
